url:
baseurl:

# Site settings
title: Efficient Interaction
email: shannon@efficientinteraction.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Shannon McHarg
  pic: 1
  position: Principal
  social:
    - title: envelope
      url: mailto:shannon@efficientinteraction.com
    - title: linkedin
      url: http://linkedin.com/in/smcharg
    - title: twitter
      url: https://twitter.com/EfficientIxD
    - title: github
      url: http://github.com/mcharg
    - title: github
      url: http://github.com/shannonmcharg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/EfficientIxD
  - title: linkedin
    url: http://linkedin.com/in/smcharg
  - title: github
    url: http://github.com/mcharg
  - title: github
    url: http://github.com/shannonmcharg

# Build settings
markdown: kramdown
permalink: pretty
