url:
baseurl:

# Site settings
title: Efficient Interaction
email: shannon@efficientinteraction.com
description: "User experience designer and researcher specializing in interaction design, information architecture, formative user research, and prototyping. My clients hire me when they have a complex problem that needs to be solved and they want someone who will solve it well and who will work efficiently."


# Team names, titles and social links
people:
- name: Shannon McHarg
  pic: 1
  position: Principal
  social:
    - title: envelope
      url: mailto:shannon@efficientinteraction.com
    - title: linkedin
      url: http://linkedin.com/in/smcharg
    - title: github
      url: http://github.com/shannonmcharg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:shannon@efficientinteraction.com
  - title: linkedin
    url: http://linkedin.com/in/smcharg
  - title: github
    url: http://github.com/shannonmcharg

# Build settings
markdown: kramdown
permalink: pretty
