url:
baseurl: 

# Site settings
title: Efficient Interaction
email: shannon@efficientinteraction.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Shannon McHarg
  pic: 1
  position: Principal
  social:
    - title: email
      url: mailto:shannon@efficientinteraction.com
    - title: linkedin
      url: http://linkedin.com/in/smcharg
    - title: twitter
      url: https://twitter.com/EfficientIxD

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
