#!/bin/sh
set -e # always good practice!

# run what we were asked to if we're already inside the container
[ -f /etc/inside-container ] && exec "$@"

# otherwise, re-exec the command inside the container
root=$(realpath "$(dirname "$0")/..")
exec docker run -it --rm \
  -p 4000:4000 \
  -v "$root:/site" \
  portfolio "$@"
